version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/aws/lambda/cognito-pre-sign-up-link-federated-user/resources"
      - "/aws/lambda/image-processor/resources"
      - "/aws/lambda/jwt-authorizer/resources"
      - "/aws/lambda-at-edge/cognito-authorizer/resources"
      - "/aws/lambda-at-edge/remove-first-part-of-path/resources"
    schedule:
      interval: "monthly"
